'use strict';

module.exports = {
    FORWARDING_FORWARD_ALL    : true,
    FORWARDING_FORWARD_NONE   : false,
    FORWARDING_FORWARD_MISSING: 'MISSING',

    SCENARIO_TYPE_SEQUENTIAL: 0,

    SCENARIO_REPEATABLE_ONE_SHOT: 1,
    SCENARIO_REPEATABLE_INFINITE: 2,

    PUBSUB_STATS_UPDATED: 'PUBSUB_STATS_UPDATED',

    STATISTICS_LOG_MODE_REALTIME: 'STATISTICS_LOG_MODE_REALTIME',
    STATISTICS_LOG_MODE_LAZY: 'STATISTICS_LOG_MODE_LAZY',
    STATISTICS_LOG_MODE_OFF: 'STATISTICS_LOG_MODE_OFF',

    ERRORS: {
        // Generic errors: 1xxx
        INCOMPLETE_OBJECT: 1001,
        
        // Playback errors: ....
        
        // Recorder errors: 4xxx
        
        ALREADY_RECORDING: 4001,
        NOT_RECORDING: 4002

        
    }
};