'use strict';

module.exports = {
    FORWARDING_FORWARD_ALL: true,
    FORWARDING_FORWARD_NONE: false,
    FORWARDING_FORWARD_MISSING: 'missing',

    PUBSUB_NOCCA_INITIALIZE_PLUGIN: 'PUBSUB_NOCCA_INITIALIZE_PLUGIN',
    PUBSUB_STATS_UPDATED: 'PUBSUB_STATS_UPDATED',
    PUBSUB_REST_ROUTE_ADDED: 'PUBSUB_REST_ROUTE_ADDED',

    ERRORS: {
        NO_ENDPOINT_FOUND: 'NO_ENDPOINT_FOUND',
        NO_RESPONSE_FOUND: 'NO_RESPONSE_FOUND',
        FORWARDER_REQUEST_ERROR: 'FORWARDER_REQUEST_ERROR'
    },

    HTTP_MESSAGE_TYPES: {
        CLIENT_REQUEST: 'CLIENT_REQUEST',
        PROXY_REQUEST: 'PROXY_REQUEST',
        PROXY_RESPONSE: 'PROXY_RESPONSE',
        PLAYBACK_RESPONSE: 'PLAYBACK_RESPONSE',
        CLIENT_RESPONSE: 'CLIENT_RESPONSE'
    }
};
