'use strict';

module.exports = {
    FORWARDING_FORWARD_ALL    : true,
    FORWARDING_FORWARD_NONE   : false,
    FORWARDING_FORWARD_MISSING: 'MISSING',

    SCENARIO_TYPE_SEQUENTIAL: 0,

    SCENARIO_REPEATABLE_ONE_SHOT: 1,
    SCENARIO_REPEATABLE_INFINITE: 2,

    PUBSUB_STATS_UPDATED: 'PUBSUB_STATS_UPDATED'
};